### ISSUE TITLE
Use Query Monitoring Rules in Redshift For Resource Intensive Queries

### ISSUE THREAD

**Issue by mugizico** [18F/identity-analytics-etl#108]
We should prioritize regular runnings queries and make sure they do not time out because of resource intensive queries like the ones mentioned in #101.
Redshift provides a way to create rules that stop adhoc queries when they exceed a certain CPU RAM threshold  https://aws.amazon.com/blogs/big-data/manage-query-workloads-with-query-monitoring-rules-in-amazon-redshift/

**Comment by lauraGgit** [comment]
Closing until we need it.
