### ISSUE TITLE
Track LexisNexis Data Reporting and Analysis

### ISSUE THREAD

**Issue by mugizico** [18F/identity-analytics-etl#109]
Use this issue to track LexisNexis' data reporting and analysis, steps such as:
* How are we going to download/upload data periodically from the Lexis Nexis RDP portal to S3 and Redshift with or without human intervention
* Creating a table in redshift that will be used for QuickSight analytics

**Comment by lauraGgit** [comment]
Needs refinement of what data, what frequency.

**Comment by lauraGgit** [comment]
not needed yet, will create story when relevant
