### ISSUE TITLE
Query/Chart for Monthly Distribution of MFA/ID Service Transactions based on SPs

### ISSUE THREAD

**Issue by akhlaqkhan** [18F/identity-analytics-etl#112]
**Is your feature request related to a problem? Please describe.**
We need to a way to track our MFA/ID Service costs for each SP in order to validate/adjust our pricing and to crosscheck our vendor invoices on monthly basis.

**Describe the solution you'd like**
- Developing a query that gives us a breakdown of number of transactions for MFA and ID services for each SP integrated with login.gov, compared with authentications and signups respectively.
- Adding a chart in the current dashboard for logins vs. mfa transcations and signups vs. ID proofing transactions (Account Verification, Document Authentication etc.)

![image](https://user-images.githubusercontent.com/13226606/43423241-dd7de518-9419-11e8-9dfe-953e44bd2c22.png)

**Comment by lauraGgit** [comment]
Converting this into an epic, and needs further refinement.

**Comment by lauraGgit** [comment]
Migrated to Jira
