### ISSUE TITLE
Looks like multiple hours have analytics outages over last month.

### ISSUE THREAD

**Issue by jrminton** [18F/identity-analytics-etl#113]
**Describe the bug**
UPDATE - The problematic rows all appear to be the 11 pm hour. Something funny might be happening at that time on many days.

It appears that we have had roughly 5 data outages over the past month. Those can be seen by looking 
at hours in the successful login reports where we have 100% success or 0% success rate, indicating very few rows were picked up.

**To Reproduce**
1. Go to https://us-west-2.quicksight.aws.amazon.com/sn/dashboards/dde4b4ad-bbeb-46ab-8eb3-7ff6cf6425da
2. Scroll down to Password Auth %.
3. See screenshot that shows 5 different hours with suspect data:
![image](https://user-images.githubusercontent.com/17144409/43435318-7b33ed56-944d-11e8-9159-ac38c18e9500.png)

**Expected behavior**
All hours have consistent data.

**Comment by lauraGgit** [comment]
Looks like this has been completed.
