### ISSUE TITLE
Task: Separate Analytics Releases into Branches 

### ISSUE THREAD

**Issue by mugizico** [18F/identity-analytics-etl#114]
**Is your feature request related to a problem? Please describe.**
Right now we push everything from `master` which forces us to push things that aren't ready to production

**Describe the solution you'd like**
Create 2 branches for analytics releasing on both `identity-analytics-etl` and `identity-analytics-devops`

- [ ] `stages/analytics-staging`
- [ ] `stages/analytics-prod`

initially both branches should point to the last lambda release that is currently in production/staging
https://github.com/18F/identity-devops/pull/945 for devops
and release v1.1 for etl

**Comment by lauraGgit** [comment]
Wait on this based off of how other repos are done.
