### ISSUE TITLE
Use IAM Credentials for Redshift Database Access

### ISSUE THREAD

**Issue by mugizico** [18F/identity-analytics-etl#115]
See https://github.com/18F/identity-devops/pull/1037
reference: https://github.com/awsdocs/amazon-redshift-management-guide/blob/master/doc_source/redshift-iam-access-control-identity-based.md#redshift-policy-resources.required-permissions.console

how to with boto3
https://boto3.readthedocs.io/en/latest/reference/services/redshift.html#Redshift.Client.get_cluster_credentials
https://stackoverflow.com/questions/44243169/connect-to-redshift-using-python-using-iam-role

**Comment by MacHu-GWU** [comment]
the IAM credential manager is not properly setup.  And this change is already reverted in https://github.com/18F/identity-analytics-etl/pull/150
