### ISSUE TITLE
Update SAM dashboard 

### ISSUE THREAD

**Issue by mugizico** [18F/identity-analytics-etl#118]
Based on our meeting with SAM, here are some of the things we can do to improve their dashboard:
- [ ] add a fully-completed user registration metric( SAM to login.gov and back to SAM successfully) 
- [ ] track raw number for return rate to agency (figure out how to transform the time series data into raw number?)
- [ ] track user drop off by domain: what user domains started registering but didn't finish within 30 days.

**Comment by MacHu-GWU** [comment]
Not hearing anything about this anymore for long.
