### ISSUE TITLE
TLS Cipher Suite Analysis

### ISSUE THREAD

**Issue by commit-dkp** [18F/identity-analytics-etl#122]
**Is your feature request related to a problem? Please describe.**

login.gov currently supports the following TLS cipher suites:

TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_CBC_SHA256

The cipher suites that match "CBC_SHA" suffer a weakness due to the order in which TLS 1.2 records are MAC'd and then encrypted.  The cipher suites that match "TLS_RSA_WITH_AES" suffer a weakness due to the static key used to encrypt the TLS premaster secret.

The only supported cipher suites that do not suffer a known weakness are:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

**Describe the solution you'd like**

To make an informed decision about which cipher suites present an acceptable risk to support and which ones do not, I'd like a forecast of the impact on users of disabling the known-weak cipher suites described above.  Specifically, how many users would find login.gov inaccessible if all known-weak cipher suites were disabled, how many users would find login.gov inaccessible if only the "CBC_SHA" cipher suites were disabled, and how many users would find login.gov inaccessible if only the "TLS_RSA_WITH_AES" cipher suites were disabled.

**Describe alternatives you've considered**
This isn't the kind of feature request where alternatives exist to be considered.

**Additional context**
The "CBC_SHA" weakness is detailed in http://www.isg.rhul.ac.uk/tls/TLStiming.pdf .
The "TLS_RSA_WITH_AES" weakness is described in some detail at https://vincent.bernat.im/en/blog/2011-ssl-perfect-forward-secrecy .

**Comment by konklone** [comment]
Sounds like this is moving to https://github.com/18F/identity-devops-private/issues.

**Comment by konklone** [comment]
(Sorry, mixing up two issues.)
