### ISSUE TITLE
TLS protocol versions

### ISSUE THREAD

**Issue by konklone** [18F/identity-analytics-etl#123]
**Is your feature request related to a problem? Please describe.**

We should be adopting newer TLS protocol versions, and deprecating older known-weak versions.

**Describe the solution you'd like**
We should be able to see what our breakdown of TLS 1.0, TLS 1.1, TLS 1.2, and TLS 1.3 usage is across our client base.

**Additional context**

@brodygov had performed some one-off analysis of TLS 1.0 usage on the platform a couple months back. I am not sure what tools were used to perform that analysis.

**Comment by monfresh** [comment]
@konklone @commit-dkp Is this still a valid issue or have we found a way to get the TLS breakdown?

**Comment by MacHu-GWU** [comment]
@brodygov could you help me understand what is this issue talking about? And any action need to take? Thank you.

**Comment by commit-dkp** [comment]
@MacHu-GWU Previously I worked with @jgrevich to spin-up a couple of hosts, one that only supports TLS 1.2 and one that supports all versions of TLS but does not support SNI.  The work that remained was to write code for the IDP, to be delivered to the user's browser, that would have the browser attempt an HTTPS request to both of those sites and report back success or failure.  In that way, we would be able to estimate the number of clients who would be impacted if support were dropped for TLS < 1.2.

**Comment by lauraGgit** [comment]
Seems like this is a devops task rather than an analytics task (in execution rather than in concept) closing
