### ISSUE TITLE
Investigate Why There is Blank Service Providers  for Monthly Active Users (By SP)

### ISSUE THREAD

**Issue by mugizico** [18F/identity-analytics-etl#129]
**Describe the bug**
Some months are not returning data when running the `monthly_active_users_by_sp` query.

**To Reproduce**
1.  ssh into jumphost and `psql` into redshift
2. run this query
```sql
# if you use a regular join, it would skip the months with blank sp.
 SELECT date_trunc('month', time) AS month,service_providers.service_provider as sp, count(DISTINCT events.user_id) AS count
   FROM events
   LEFT JOIN service_providers ON events.service_provider = service_providers.events_sp
  GROUP BY sp, month
  ORDER BY month DESC, count DESC;

```

3. You should see that for `month >= 2017-11-01` the sp column will be empty

**Expected behavior**
every month should return a breakdown of active users by SP like so
```
2017-12-01 00:00:00 | ttp                                                |  321343
 2017-12-01 00:00:00 | cbp-jobs                                           |   10666
 2017-12-01 00:00:00 | USDS-hipchat                                       |      89
 2017-12-01 00:00:00 | oars                                               |      81
```

Note: 
a good place to start is looking  if the schema/DML changed at that point.

**Comment by monfresh** [comment]
The only months where there is no SP data at all are September and October 2017. This makes sense because we didn't add the top-level `service_provider` attribute to every event until October 31:  https://github.com/18F/identity-idp/pull/1759
