### ISSUE TITLE
Task: We don't have dev environment for Redshift, the staging Redshift are properly used. (Tech Debt)

### ISSUE THREAD

**Issue by MacHu-GWU** [18F/identity-analytics-etl#136]
We currently execute the same lambda function on staging data source in s3 bucket, and then copy it to staging redshift. But the staging data source is different from the prod data source. **I think we suppose to use it for testing, but we are not using it properly**. 

Now analytic script development is based on prod Redshift. Which is **not safe** (dev should not on prod Redshift), and **also not convenience** (JumpHost doesn't have any dev tools)

**Impact**: High

1. We have no choice other than doing ETL Development on prod Redshift.
2. It is almost impossible to do any analytic development on prod Redshift. Because the Jumphost doesn't have any development tools.
3. Lack of dev environment for analytics, scripts are not organized and tested.

**Solution**

- [ ] Use staging Redshift for development, Properly sync part of the dataset to staging Redshift.
- [ ] Grant analytics developer programmatic access to staging Redshift, and restructure the analytic repo, properly test the Analytic Code.
- [ ] Grant Business end-user access from a secure environment such as jump host, only allow non-programmatic, read-only, sql style access.

**Effort to take**: High

1. Need further explore and discussing for the solution. How to properly sync dataset between prod and staging is tricky.
2. Need help from DevOps team.

**Benefit**: High

**Comment by lauraGgit** [comment]
Seems like this will be resolved by kinesis shift
