### ISSUE TITLE
Task: Get onboarded to Kibana

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#179]
Explore data on Kibana to assess exploration pipeline

**Comment by MacHu-GWU** [comment]
# Note: Explore data on Kibana (Not Finalized)

The how-to guide will be posted here.

1. Clone this repo to your local: https://github.com/18F/identity-devops
2. Bash: ``./bin/ssh-instance -L 5601:localhost:5601 asg-prod-elk``
3. Enter the console: ``localhost:5601/app/kibana``

and go to this url:
localhost:5601/app/kibana

**Comment by lauraGgit** [comment]
blocked until kibana instance back online

**Comment by lauraGgit** [comment]
getting closer- now getting permission denied

**Comment by lauraGgit** [comment]
finally got in! success
