### ISSUE TITLE
Task: user flow diagram

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#180]
## User story
As a new member of the analytics team, **I would like to see a diagram of the data pipeline, so that I can understand the implications of the data quality and breath**.

## Notes
* What is the value to the user in this story?*
better grok our data structures

* What are things we should consider when making this story *
this will be evolving
## Acceptance Criteria
- [ ]

## Tasks to complete the story
- [ ] 

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by MacHu-GWU** [comment]
@lauraGgit I can draw it when I finished task in this Sprint

**Comment by lauraGgit** [comment]
# Draft Datapipeline diagram
![image](https://user-images.githubusercontent.com/5840989/52372558-787b9680-2a26-11e9-923e-6d1beb474b10.png)


## [Mermaid Chart](https://mermaidjs.github.io/) to generate [this](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggTFJcbkFbUHJvZHVjdGlvbiBBcHBsaWNhdGlvbl0gLS0-fFVzZXIgZHJpdmVuIGV2ZW50fCBCW0FXUyBDbG91ZFdhdGNoXVxuQSAtLiBVc2VyIGRyaXZlbiBldmVudC4tPiBMW0dvb2dsZSBBbmFseXRpY3NdXG5CIC0tPiBDW0xhbWJkYSBQYXJzZXJdXG5DIC0tPiBHW0ludGVybWVkaWF0ZSBTMyBidWNrZXRdXG5EIC0tPiBJW0xhbWRiYSAtUmVkU2hpZnQgTG9hZGVyXVxuSSAtLT4gSltSZWRTaGlmdF1cbkogLS0-IEhbQVdTIFF1aWNrU2l0ZV1cbkogLS4tPiBLW0JsYXplcl1cbkIgLS0-IERbTG9nc3Rhc2hdXG5EIC0tPiBFW0VsYXN0aVNlYXJjaF1cbkUgLS0-IEZbS2liYW5hXVxuXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ):
```
graph LR
A[Production Application] -->|User driven event| B[AWS CloudWatch]
A -. User driven event.-> L[Google Analytics]
B --> C[Lambda Parser]
C --> G[Intermediate S3 bucket]
D --> I[Lamdba -RedShift Loader]
I --> J[RedShift]
J --> H[AWS QuickSite]
J -.-> K[Blazer]
B --> D[Logstash]
D --> E[ElastiSearch]
E --> F[Kibana]
```

**Comment by lauraGgit** [comment]
## Update per Sanhe's comments:
![image](https://user-images.githubusercontent.com/5840989/52373536-ea54df80-2a28-11e9-9b16-d2fbba1934b1.png)

## [Live Link](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggTFJcbkFbUHJvZHVjdGlvbiBBcHBsaWNhdGlvbl0gLS0-fFVzZXIgZHJpdmVuIGV2ZW50fCBCW0FXUyBDbG91ZFdhdGNoXVxuQSAtLiBVc2VyIGRyaXZlbiBldmVudC4tPiBMW0dvb2dsZSBBbmFseXRpY3NdXG5EIC0tPiBNW1JhdyBkYXRhIHMzIGJ1Y2tldF1cbk0gLS0-IENbTGFtYmRhIFBhcnNlcl1cbkMgLS0-IEdbSG90IGJ1Y2tldCAtSW50ZXJtZWRpYXRlIFMzIGJ1Y2tldF1cbkcgLS0-IElbTGFtZGJhIC1SZWRTaGlmdCBMb2FkZXJdXG5JIC0tPiBKW1JlZFNoaWZ0XVxuSiAtLT4gSFtBV1MgUXVpY2tTaXRlXVxuSiAtLi0-IEtbQmxhemVyXVxuQiAtLT4gRFtMb2dzdGFzaF1cbkQgLS0-IEVbRWxhc3RpU2VhcmNoXVxuRSAtLT4gRltLaWJhbmFdXG5cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

## Code to generate
```
graph LR
A[Production Application] -->|User driven event| B[AWS CloudWatch]
A -. User driven event.-> L[Google Analytics]
D --> M[Raw data s3 bucket]
M --> C[Lambda Parser]
C --> G[Hot bucket -Intermediate S3 bucket]
G --> I[Lamdba -RedShift Loader]
I --> J[RedShift]
J --> H[AWS QuickSite]
J -.-> K[Blazer]
B --> D[Logstash]
D --> E[ElastiSearch]
E --> F[Kibana]
```

**Comment by lauraGgit** [comment]
Now with Kinesis future implementation:
![image](https://user-images.githubusercontent.com/5840989/52419390-f939a180-2abd-11e9-8689-416e6e6a7afa.png)

```
graph TD
A[Production Application] -->N[User driven event]
N -.-> L[Google Analytics]
N --> B[AWS CloudWatch]
B -.-> O[Kinesis]
O-.->J
D --> M[Raw data s3 bucket]
M --> C[Lambda Parser]
C --> G[Hot bucket -Intermediate S3 bucket]
G --> I[Lamdba -RedShift Loader]
I --> J[RedShift]
J --> H[AWS QuickSite]
J -.-> K[Blazer]
N --> D[Logstash]
D --> E[ElastiSearch]
E --> F[Kibana]

```

**Comment by MacHu-GWU** [comment]
@lauraGgit I think we can mark this one https://github.com/18F/identity-analytics-etl/issues/180#issuecomment-461181600, as ``out-of-dated``.

**Comment by MacHu-GWU** [comment]
And I think we can mark this as done
