### ISSUE TITLE
ETL Pipeline need a Worker for undone data file

### ISSUE THREAD

**Issue by MacHu-GWU** [18F/identity-analytics-etl#195]
## User story

I would like to improve the data quality in Redshift.

Now the ETL pipeline is triggered by S3 object creation event. If the parser failed on a data file, we leave nothing in the Hot Bucket. **We need another worker to trigger the parser for undone data file**.

The reason that I don't recommend to add retry to the parser is that ``sometimes retry is just not able to make it better``.

## Notes

* What is the value to the user in this story?*

- Avoid missing data in Redshift.
- This worker provides the flexibility of doing undone data file at any time we need.

## Acceptance Criteria

- [ ]

## Tasks to complete the story

- [ ] 

## Definition of Done

- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
@MacHu-GWU if we move to kinesis, will we still need this?

**Comment by MacHu-GWU** [comment]
I think we still needed it in a different way. If the Kinesis ETL pipeline is broken, we still need something to trigger it for missing date time range after we fixed it.

If an ETL system is not 100% stable, we need this **REDO** things anyway.

**Comment by lauraGgit** [comment]
ok, that's helpful

**Comment by MacHu-GWU** [comment]
For example, every time the current ETL pipeline brokes, devops folks like Andy needs to spend lots of time on *REDO* the missing data. It should be automated.

**Comment by lauraGgit** [comment]
migrated to jira
