### ISSUE TITLE
Create an Analytics onboarding Wiki.

### ISSUE THREAD

**Issue by cacraig** [18F/identity-analytics-etl#38]
Since I'm doing this currently, I'd like to organize my findings into a Wiki, so future folks can do this a bit quicker.

(1) Env set up.
(2) AWS permissions/accounts set up (and who to contact about obtaining these).
(3) Enabling Jumphost access.
(4) Deployment.
(5) System Architecture.
(6) ... ?

**Comment by lauraGgit** [comment]
This seems to be covered by existing wiki updates
