### ISSUE TITLE
remove uploaded_files check and replace with count?

### ISSUE THREAD

**Issue by jbramble-gov** [18F/identity-analytics-etl#59]
@cacraig I noticed that the safe query execution for checking uploaded_files takes on average 1 min to execute in peak load times now. This is probably the largest bottleneck on performance currently, as copies currently take .5 seconds to execute. 

Could we speed this up by doing:
``` sql
select count(1)
from table
where s3filename = trigger_file;
```

This should work since the lambda is triggered by 1 file. so instead of getting all uploaded files and iterating over them to check if the file is in that list,
could we instead run the above mentioned query and check if the count is equal to zero?

**Comment by lauraGgit** [comment]
Already fixed
